### ISSUE TITLE
Principle 1 - Prioritize delivering impact for British Columbians

### ISSUE THREAD

**Issue by glam-bert** [bcgov/digital-principles#8]
I think we can more strongly acknowledge that improving the ease and efficiency by which the public service delivers services delivers impact for British Columbians. When public servants are able to use digital services in their own work, even if these digital services are not citizen-facing, the speed and relevancy of our response to citizen needs can be greatly improved. Let's make it clearer that prioritizing impact to British Columbians does not mean prioritizing paint over engine.

**Comment by AlexanderRitchie** [comment]
Agreed - saw a twitter thread earlier that made it sound like doing digital is about building public facing services - this downplays and misses the importance of 'Digital on the Inside', which to me is a pre-cursor or at least parallel stream to digital public facing services.

Possible edit:
Government exists to improve peoples’ lives. Digital services should support this goal. Focus on **DIGITAL SERVICES, CAPABILITIES, and TOOLS THAT MEET** citizens’ needs **AND EXPECTATIONS, AND IMPROVE GOVERNMENT SERVICE PROVISION** ;build services for outcomes rather than outputs; deliver sustainable services through judicious use of public resources.

**Comment by sarabose** [comment]
We've made quite a few changes to Principle 1 in v. 0.2 in response to your thoughtful feedback. Let us know if you think Principle 1 could be further improved.
